#!/bin/sh

# TODO: read from file containing network configuration
# TODO: create and configure network bridge
# TODO: static ips?

# Key pair to SSH into VMs
[ -f ssh.key ] && [ -f ssh.key.pub ] || {
	echo "Generating ssh.key keypair..."
	ssh-keygen -N "" -f ssh.key || exit 1
}

[ -f base.img ] || {
	echo "Generating base.img..."
	debvm-create \
		-h base -o base.img -r unstable -z 2GB -k ssh.key.pub \
		-- "http://deb.debian.org/debian" "deb [trusted=yes] https://defo.ie/debian ./" \
		--include libcurl4=8.4.0-2.1~1.gbp221d8f,curl=8.4.0-2.1~1.gbp221d8f \
		--include ca-certificates,iproute2,iputils-ping,dnsutils,xxd || exit 1
}

# Network bridge
# ip link add name br0 type bridge
# ip addr add 172.20.0.1/16 dev br0
# ip link set dev br0 up
# dnsmasq --interface=br0 --bind-interfaces --dhcp-range=172.20.0.2,172.20.255.254
